using System;
using System.Collections.Generic;
using BPMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace BPMS.Domain.Context;

public partial class BPMS_Context : DbContext
{
    public BPMS_Context()
    {
    }

    public BPMS_Context(DbContextOptions<BPMS_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Dsaudct> Dsaudcts { get; set; }

    public virtual DbSet<Dsauddt> Dsauddts { get; set; }

    public virtual DbSet<Dsaudmt> Dsaudmts { get; set; }

    public virtual DbSet<Dsddert> Dsdderts { get; set; }

    public virtual DbSet<Dsiradt> Dsiradts { get; set; }

    public virtual DbSet<Dsisdst> Dsisdsts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseOracle("User Id=bpmsuser;Password=bpmsuser;Data Source= (DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = ntoraclecmpq)(PORT = 1521))(CONNECT_DATA = (SID = ORCL)))");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("BPMSUSER")
            .UseCollation("USING_NLS_COMP");

        modelBuilder.Entity<Dsaudct>(entity =>
        {
            entity.HasKey(e => new { e.DsaudmSrl, e.Seq }).HasName("DSAUDC_PK");

            entity.HasOne(d => d.DsaudmSrlNavigation).WithMany(p => p.Dsaudcts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DSAUDC_DSAUDM_FK");
        });

        modelBuilder.Entity<Dsauddt>(entity =>
        {
            entity.HasKey(e => new { e.DsaudmSrl, e.DsisdsSrl }).HasName("DSAUDD_PK");

            entity.HasOne(d => d.DsaudmSrlNavigation).WithMany(p => p.Dsauddts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DSAUDD_DSAUDM_FK");

            entity.HasOne(d => d.DsisdsSrlNavigation).WithMany(p => p.Dsauddts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DSAUDD_DSISDS_FK");
        });

        modelBuilder.Entity<Dsaudmt>(entity =>
        {
            entity.HasKey(e => e.Srl).HasName("DSAUDM_PK");

            entity.Property(e => e.Srl).ValueGeneratedNever();
            entity.Property(e => e.DateKk).IsFixedLength();
            entity.Property(e => e.DateKm).IsFixedLength();
            entity.Property(e => e.DateT).IsFixedLength();
        });

        modelBuilder.Entity<Dsddert>(entity =>
        {
            entity.HasKey(e => new { e.DsauddDsaudmSrl, e.DsauddDsisdsSrl, e.DsiradSrl }).HasName("DSDDER_PK");

            entity.HasOne(d => d.DsiradSrlNavigation).WithMany(p => p.Dsdderts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DSDDER_DSIRAD_FK");

            entity.HasOne(d => d.DsauddDs).WithMany(p => p.Dsdderts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DSDDER_DSAUDD_FK");
        });

        modelBuilder.Entity<Dsiradt>(entity =>
        {
            entity.HasKey(e => e.Srl).HasName("DSIRAD_PK");

            entity.Property(e => e.Srl).ValueGeneratedNever();
        });

        modelBuilder.Entity<Dsisdst>(entity =>
        {
            entity.HasKey(e => e.Srl).HasName("DSISDS_PK");

            entity.Property(e => e.Srl).ValueGeneratedNever();
        });
        modelBuilder.HasSequence("ACSTRC_SEQ", "ADMIN");
        modelBuilder.HasSequence("ANAGRD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ANAGRM_SEQ", "ADMIN");
        modelBuilder.HasSequence("ANBURS_SEQ", "ADMIN");
        modelBuilder.HasSequence("ANSNPT_BPMS_SEQ", "ADMIN");
        modelBuilder.HasSequence("APPROJ_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARCATG_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARCHIVE_SEQUENCE", "ADMIN");
        modelBuilder.HasSequence("ARDOCL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARERNTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARMAPCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARMSTRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARPACKT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARPRDCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARPRTCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARSTNDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARTSTPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ARUSCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("AUDIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BABULD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAFORM_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAMV95_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAMVBR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAMVPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAMVST_SEQ", "ADMIN");
        modelBuilder.HasSequence("BAPLAK_SEQ", "ADMIN");
        modelBuilder.HasSequence("BASCTN_SEQ", "ADMIN");
        modelBuilder.HasSequence("BASLON_SEQ", "ADMIN");
        modelBuilder.HasSequence("BASTPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("BASTTN_SEQ", "ADMIN");
        modelBuilder.HasSequence("BASTTR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BATRSF_SEQ", "ADMIN");
        modelBuilder.HasSequence("BATRST_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIACCD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIACCS_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIACCU_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBADLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBDLDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBLGDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOML_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPI_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPK_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPM_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPO_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPP_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPS_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBOPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIBPLGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BICOPD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BICOPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDCMD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDECB_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDECD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDECE_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDECP_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIDECR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIIKPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIMAPC_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIMAPGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIMPOW_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIPRTC_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIPRTR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRDBD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRDBH_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRFQB_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRFQP_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRFQR_SEQ", "ADMIN");
        modelBuilder.HasSequence("BIRFQTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISAPDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISAPPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISAPRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISSRC_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISTDGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISUBM_SEQ", "ADMIN");
        modelBuilder.HasSequence("BISUPN_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITECD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITECH_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITECL_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITECNO_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITECP_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITJCD_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITNAH_SEQ", "ADMIN");
        modelBuilder.HasSequence("BITNAHA_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPD1CMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPD1SGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPD2CMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPDBCMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPM1CMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPM1SGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPTG01T_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("BPTGD1T_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPTGD2T_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPTGD3T_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPTGM1T_SEQ", "ADMIN");
        modelBuilder.HasSequence("BPTSJMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CABONH_SEQ", "ADMIN");
        modelBuilder.HasSequence("CABONI_SEQ", "ADMIN");
        modelBuilder.HasSequence("CABONP_SEQ", "ADMIN");
        modelBuilder.HasSequence("CAETCP_SEQ", "ADMIN");
        modelBuilder.HasSequence("CBESLH_SEQ", "ADMIN");
        modelBuilder.HasSequence("CBMEEH_SEQ", "ADMIN");
        modelBuilder.HasSequence("CBPERS_SEQ", "ADMIN");
        modelBuilder.HasSequence("CBRSME_SEQ", "ADMIN");
        modelBuilder.HasSequence("CEOPERT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CERQSTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CEVSTRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CGCOLR_SEQ", "ADMIN");
        modelBuilder.HasSequence("CGFRM_SEQ", "ADMIN");
        modelBuilder.HasSequence("CGITM_SEQ", "ADMIN");
        modelBuilder.HasSequence("CGMAPS_SEQ", "ADMIN");
        modelBuilder.HasSequence("CGTAG_SEQ", "ADMIN");
        modelBuilder.HasSequence("CMMDLC_SEQ", "ADMIN");
        modelBuilder.HasSequence("CMMILP_SEQ", "ADMIN");
        modelBuilder.HasSequence("CMPJMR_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJFC_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJNP_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJNPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJOT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJPRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPJRST_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPRAD_SEQ", "ADMIN");
        modelBuilder.HasSequence("CNPRJH_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTAMCTMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTATRS_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTCONT_TMP_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTDARAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTENCDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTLGBS_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTLOGS_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTSABYT_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTSALH_SEQ", "ADMIN");
        modelBuilder.HasSequence("CTSCAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("DBA_LOGCONFIG_SEQ", "ADMIN");
        modelBuilder.HasSequence("DEPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("DEPTREE_SEQ", "ADMIN");
        modelBuilder.HasSequence("DEREQS_SEQ", "ADMIN");
        modelBuilder.HasSequence("DSPISM_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBA_ARCHIVE_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBACCI_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBCFIH_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBCRAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBCRDA_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBERJD_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBERJH_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBINSA_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBLADT_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBMSVH_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBORDR_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBPFAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBPLCN_SEQ", "ADMIN");
        modelBuilder.HasSequence("EBPLOG_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECANDS_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECCHNM_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECDAAA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECDEPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECEICH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECEMAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECEMAPA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECENCH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECESLA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECFWUP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECGRES_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECIMPLA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECIMPLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECIMPLTA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECINFO_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECMRML_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECNEED_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECONLM_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECONLP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECONLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECPRNU_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECPYSH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECRQYD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECRTBD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECRTMD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ECSTCA_SEQ", "ADMIN");
        modelBuilder.HasSequence("EDINEW_SEQ", "ADMIN");
        modelBuilder.HasSequence("EMP_SEQ", "ADMIN");
        modelBuilder.HasSequence("EPCHRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_00", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_01", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_02", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_2", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_98", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_99", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_LAST", "ADMIN");
        modelBuilder.HasSequence("GADOCM_SEQ_NO_NEW", "ADMIN");
        modelBuilder.HasSequence("GADOCM_TYP1_SEQ", "ADMIN");
        modelBuilder.HasSequence("GADOCM_TYP2_SEQ", "ADMIN");
        modelBuilder.HasSequence("GADOCM_TYP3_SEQ", "ADMIN");
        modelBuilder.HasSequence("GASTVS_SEQ", "ADMIN");
        modelBuilder.HasSequence("IB_MVG", "ADMIN");
        modelBuilder.HasSequence("IB_SRL", "ADMIN");
        modelBuilder.HasSequence("IBMSVS_SEQ", "ADMIN");
        modelBuilder.HasSequence("IBSDRS_SEQ", "ADMIN");
        modelBuilder.HasSequence("IBSMRS_SEQ", "ADMIN");
        modelBuilder.HasSequence("IBSTRS_SEQ", "ADMIN");
        modelBuilder.HasSequence("ICBLAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ICLDGB_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPAUDIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPCEEX_CERT_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPCEEX_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPCERC_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPCERT_CERTNO_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPCERT_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPLBBX_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPLBPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPPROD_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPPRSS_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPQREQ_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("IPTRPT_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1422311", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1422437", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1422451", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1425560", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1433529", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1433539", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1433545", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_172473", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_1807888", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_957069", "ADMIN");
        modelBuilder.HasSequence("ISEQ$$_999178", "ADMIN");
        modelBuilder.HasSequence("ISFCRP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ISMNGR_SEQ", "ADMIN");
        modelBuilder.HasSequence("ISSACT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ISSPMRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKARZB_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKARZS_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKBOMNT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKBOUDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKBOUST_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKCMSG_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKCRPM_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKCRPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKDCOPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKFOACT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKPCOPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKPOACT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JKUSERT_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSANSR_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSFCTR_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSGROP_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSGRPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSGRQS_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSPOLL_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSQSTN_SEQ", "ADMIN");
        modelBuilder.HasSequence("JSRSPN_SEQ", "ADMIN");
        modelBuilder.HasSequence("KAITM_SEQ", "ADMIN");
        modelBuilder.HasSequence("KBFM58_SEQ", "ADMIN");
        modelBuilder.HasSequence("KBIK58T_SEQ", "ADMIN");
        modelBuilder.HasSequence("KBRQRJ_SEQ", "ADMIN");
        modelBuilder.HasSequence("KD332H_SEQ", "ADMIN");
        modelBuilder.HasSequence("KD332Z_SEQ", "ADMIN");
        modelBuilder.HasSequence("KDDETL_SEQ", "ADMIN");
        modelBuilder.HasSequence("KDHEAD_SEQ", "ADMIN");
        modelBuilder.HasSequence("KDINSH_SEQ", "ADMIN");
        modelBuilder.HasSequence("KDTRND_SEQ", "ADMIN");
        modelBuilder.HasSequence("KDTRNH_SEQ", "ADMIN");
        modelBuilder.HasSequence("KLCLEM_NO_SEQ", "ADMIN");
        modelBuilder.HasSequence("KLCLEM_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("KLSPCL_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPCINV_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPEXIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPISSU_NUM_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPISSU_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPKINV_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPKLMR_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPLINV_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPREQH_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPRPTL_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPSTRN_SEQ", "ADMIN");
        modelBuilder.HasSequence("KPSUSR_SEQ", "ADMIN");
        modelBuilder.HasSequence("KSADTM_SEQ", "ADMIN");
        modelBuilder.HasSequence("MCPRID_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEANSRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MECFCNT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MECUSTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEEVALT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEINDXT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEMNGRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEQSSPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEQSTN_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEREST_SEQ", "ADMIN");
        modelBuilder.HasSequence("MERSLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MESMPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("MESPCTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MESPDG_SEQ", "ADMIN");
        modelBuilder.HasSequence("MEVLFLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MFCHHHT_SEQ", "ADMIN");
        modelBuilder.HasSequence("MICROSOFTSEQDTPROPERTIES", "ADMIN");
        modelBuilder.HasSequence("MIORIKS", "ADMIN");
        modelBuilder.HasSequence("MIORIKS1", "ADMIN");
        modelBuilder.HasSequence("MSSPPM1_SEQ", "ADMIN");
        modelBuilder.HasSequence("MSSPPM2_SEQ", "ADMIN");
        modelBuilder.HasSequence("MSSPPM3_SEQ", "ADMIN");
        modelBuilder.HasSequence("MSTPPM1_SEQ", "ADMIN");
        modelBuilder.HasSequence("MSTPPM2_SEQ", "ADMIN");
        modelBuilder.HasSequence("MSTPPM3_SEQ", "ADMIN");
        modelBuilder.HasSequence("MYSEQ", "ADMIN");
        modelBuilder.HasSequence("NDASQD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASQH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASSD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASSF_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASSH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASSP_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDASSQ_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDBOMX_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCARH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCART_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCARTT_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCARX_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCHGD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCHGH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCHRE_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCOMF_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCOMH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPCD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPCI_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPCM_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPLH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPLW_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCPRTT_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDCRED_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDDAPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMDSB_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMDSM_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMDSS_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMNUD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMNUP_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMRPH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDMRPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDPRDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDPRTM_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDPRTO_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDPRTOA_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDR_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSELH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSEND_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTLM_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTLMA_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTLP_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTLPA_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDSTYP_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDTASH_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDTNDD_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDTNDR_SEQ", "ADMIN");
        modelBuilder.HasSequence("NDTNDRA_SEQ", "ADMIN");
        modelBuilder.HasSequence("OGPTSK_SEQ", "ADMIN");
        modelBuilder.HasSequence("OR_ORDLVO_GRP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORARZH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDA91S", "ADMIN");
        modelBuilder.HasSequence("ORDEPA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDEPD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDEPH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDEPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDEPS_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORDLOI_TBL_SRL", "ADMIN");
        modelBuilder.HasSequence("ORDLVOT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFBAD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFBAH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFBAM_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFBRD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFBRH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFINV_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFORB_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFORD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFRQH_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORFSCH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORINVD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORINVH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORINVZ_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORITRK_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORKCAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORKERR_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORKNBST_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORKPIL_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORKSNC_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHB_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHF_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHH_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHI_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHJ_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORNTHZ_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORORDT_NUM", "ADMIN");
        modelBuilder.HasSequence("ORORDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORORND_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORPRDD_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORPRIC_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORSAPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORST06_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORTABA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORTABAA_SEQ", "ADMIN");
        modelBuilder.HasSequence("ORTAHH_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSANSWT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSAUDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSCONT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSCOPDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSCOPMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSDICOT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSDVPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSDVTST_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSEDUCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSEMES_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSEMPLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSENCHIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSENCHT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSENCIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSEQUPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSERORT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSERRPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSEXHBT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSFDBK_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSFRPRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSFRWLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSFWLIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSGSTGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSICHAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSIDTIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSIDTMT_SE", "ADMIN");
        modelBuilder.HasSequence("OSIDTMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSIEXBT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSINVDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSINVMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSINVST_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSIVIST_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSLGPRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSMSAIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSNAVGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSNTECT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPALTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPAPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPROD_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPRSL_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPRSNT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSPSTGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSQAPIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSQAPST_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSQATCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSQFDPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSQUTNT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSATCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSCHAT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSHRST_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSILIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSILYT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSITET_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSLVI_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSPCIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSSTRGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSTMIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSUSERT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSVISIT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSXPATT_SEQ", "ADMIN");
        modelBuilder.HasSequence("OSXPORT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PAANBS_SEQ", "ADMIN");
        modelBuilder.HasSequence("PAANLP_SEQ", "ADMIN");
        modelBuilder.HasSequence("PAANMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PACPRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("PAL_ID_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("PAPICC_SEQ", "ADMIN");
        modelBuilder.HasSequence("PASCRP_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBBMPMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBPRTCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBPSQD_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBPSQH_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBPSQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PBSBOMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PEPRTST_SEQ", "ADMIN");
        modelBuilder.HasSequence("PEQUEST_SEQ", "ADMIN");
        modelBuilder.HasSequence("PETYPQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKCONDA_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKPAKD_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKPALDA_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKPIND_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKPRIC_SEQ", "ADMIN");
        modelBuilder.HasSequence("PKPRTSA_SEQ", "ADMIN");
        modelBuilder.HasSequence("POLING_SEQ", "ADMIN");
        modelBuilder.HasSequence("POLINGT_SEQ", "ADMIN");
        modelBuilder.HasSequence("POQUES_SEQ", "ADMIN");
        modelBuilder.HasSequence("POQUEST_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRBRBR_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRBRSC_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRCHTY_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRCIRW_SEQ", "ADMIN");
        modelBuilder.HasSequence("PREDST_SEQ", "ADMIN");
        modelBuilder.HasSequence("PREMPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("PREMTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRPLTRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRQLFY_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRRQBD_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRRQBLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRSRVQ_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRSRVR_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRSVQC_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRTMDTT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRTMVJT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRTRVDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PRTRVMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PYFACT_SEQ", "ADMIN");
        modelBuilder.HasSequence("PYPYDD_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMACTN_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMCUAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMCUDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMEFCR_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMFNAN_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMLABL_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMCUA_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMCUD_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMOAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMONI_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMSAA_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMSAD_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMSAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMSUD_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMMTAC_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMPLAN_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMPRAC_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMPROD_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMPSCR_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMPSFN_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMSAAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMSADT_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMSCND_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMSUAP_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMSUDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMTRQD_SEC", "ADMIN");
        modelBuilder.HasSequence("QMTRQE_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMWARN_SEQ", "ADMIN");
        modelBuilder.HasSequence("QMWATC_SEQ", "ADMIN");
        modelBuilder.HasSequence("QPIKCQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("REPORTS_JOBS", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SAADJM_SEQ", "ADMIN");
        modelBuilder.HasSequence("SAFCTHT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SAFCTM_SEQ", "ADMIN");
        modelBuilder.HasSequence("SCPRCI_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SDFOIL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SDPRIS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SDPRMA_SEQ", "ADMIN");
        modelBuilder.HasSequence("SEBLKLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SEMCOG_SEQ", "ADMIN");
        modelBuilder.HasSequence("SEMCVR_SEQ", "ADMIN");
        modelBuilder.HasSequence("SEPNTMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SEQ_GEN", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SEQMAH1", "ADMIN");
        modelBuilder.HasSequence("SEVSTRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGBDPR_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGCHNPART_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGFRML_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGFRMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLCD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLCO_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLJP_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLMP_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLOB_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLOL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLTP_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGGLWG_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGLICD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGMILE_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGMILS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGMODL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SGRELOC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHCLAS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHDAPLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHDDPLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHDOZI_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHLACKT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHLACKT_SEQ1", "ADMIN");
        modelBuilder.HasSequence("SHLINE_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHLNST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHMAND_SRL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHMAPLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHMDCS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHMDYD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHMDYT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHPLNM_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHPLNW_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHPRCL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHPRCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHPRST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHSALN_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHSTINT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHTRIM_SEQ", "ADMIN");
        modelBuilder.HasSequence("SHYAPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLCOMR_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLEMDD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLEMDRT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLORD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLPAKN_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLPGSC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLPLSCT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLPRIC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SLRQUS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMCRRQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDD_OP_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SMP_VDE_EVENT_ARCHIVE_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SMP_VDE_EVENT_OCCURRENCE_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDE_EVENT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDE_METRIC_THRESHOLDS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDE_NODE_UPDOWN_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SMP_VDE_TRY_REMOVE_EVENT_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SMP_VDJ_JOB_ID_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDJ_JOB_OUTPUT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDM_PAGING_CRR_ID_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDM_SEQUENCE_NUM", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SMP_VDN_GROUP_LIST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDN_TARGET_LIST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDN_TARGET_TYPE_DEFN_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDP_REGION_ID_SEQ", "ADMIN");
        modelBuilder.HasSequence("SMP_VDS_SESSIONS_SEQUENCE", "ADMIN");
        modelBuilder.HasSequence("SMP_VDU_OBJECTS_SEQUENCE", "ADMIN");
        modelBuilder.HasSequence("SMP_VDU_PRINCIPALS_SEQUENCE", "ADMIN");
        modelBuilder.HasSequence("SOCASS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SOCOMP_SEQ", "ADMIN");
        modelBuilder.HasSequence("SOCOMPA_SEQ", "ADMIN");
        modelBuilder.HasSequence("SOPLCY_SEQ", "ADMIN");
        modelBuilder.HasSequence("SOUSER_SEQ", "ADMIN");
        modelBuilder.HasSequence("SPIKCQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRASN_IK_GET", "ADMIN");
        modelBuilder.HasSequence("SRASNH_LOW_NUM", "ADMIN").IncrementsBy(-1);
        modelBuilder.HasSequence("SRASNH_NUM", "ADMIN");
        modelBuilder.HasSequence("SRASNH_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRASTS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRAUSR_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCDMA_GRP_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCENC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCISU_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCSSR_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCTMD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRCURV_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRDLVS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRENTC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRERRC_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRF40H_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRF42H_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRFM40_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRFM42_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRFM57_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRFSYN_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRIPRD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRIS40_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKBFQ_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKEXL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKHIS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKINF_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKK57_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKNBST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRKUSR_SEQ", "ADMIN").IsCyclic();
        modelBuilder.HasSequence("SRLDTM_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRMLK_NUM", "ADMIN");
        modelBuilder.HasSequence("SRMLK_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRMWDT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRODL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPALB_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPALD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPALH_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPALHT_DOCNO_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPLNMT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRPRCD_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRRPTL_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRSYNH_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRTCOST_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRTPLNT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRTRANS_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRTRCK_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRTRPT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SRWTRN_SEQ", "ADMIN");
        modelBuilder.HasSequence("SSACTY_SEQ", "ADMIN");
        modelBuilder.HasSequence("ST_CONT_ERR_SEQ", "ADMIN");
        modelBuilder.HasSequence("ST_CONT_KP_SEQ", "ADMIN");
        modelBuilder.HasSequence("ST_CONT_SEQ", "ADMIN");
        modelBuilder.HasSequence("STADJM_SEQ", "ADMIN");
        modelBuilder.HasSequence("STBILM_SEQ", "ADMIN");
        modelBuilder.HasSequence("STBLDF_SEQ", "ADMIN");
        modelBuilder.HasSequence("STCOOV_SEQ", "ADMIN");
        modelBuilder.HasSequence("STPRCLT_SEQ", "ADMIN");
        modelBuilder.HasSequence("STPREQT_SEQ", "ADMIN");
        modelBuilder.HasSequence("SW", "ADMIN");
        modelBuilder.HasSequence("SWMDEF_SEQ", "ADMIN");
        modelBuilder.HasSequence("TEST_SEQ", "ADMIN").IncrementsBy(-1);
        modelBuilder.HasSequence("TSTASK_SEQ", "ADMIN");
        modelBuilder.HasSequence("TSTKDS_SEQ", "ADMIN");
        modelBuilder.HasSequence("TUCNPS_SEQ", "ADMIN");
        modelBuilder.HasSequence("TUHMRQ_SEQ", "ADMIN");
        modelBuilder.HasSequence("UA_SAPCO_SID_SEQ", "ADMIN");
        modelBuilder.HasSequence("UALOGWT_SEQ", "ADMIN");
        modelBuilder.HasSequence("UAMAIL_SEQ", "ADMIN");
        modelBuilder.HasSequence("UAPPAC_SEQ", "ADMIN");
        modelBuilder.HasSequence("UASYSUT_SEQ", "ADMIN");
        modelBuilder.HasSequence("UATABD_SEQ", "ADMIN");
        modelBuilder.HasSequence("UATABH_SEQ", "ADMIN");
        modelBuilder.HasSequence("UATABP_SEQ", "ADMIN");
        modelBuilder.HasSequence("UATOPU_SEQ", "ADMIN");
        modelBuilder.HasSequence("UAWBLL_SEQ", "ADMIN");
        modelBuilder.HasSequence("UAWBPL_SEQ", "ADMIN");
        modelBuilder.HasSequence("WSQUEU_SEQ", "ADMIN");
        modelBuilder.HasSequence("XPLAIN_SEQ", "ADMIN");
        modelBuilder.HasSequence("XPPKGD_SEQ", "ADMIN");
        modelBuilder.HasSequence("XPPKGD_SEQ_1", "ADMIN");
        modelBuilder.HasSequence("XPPKNG_SEQ", "ADMIN");
        modelBuilder.HasSequence("XXX", "ADMIN");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
